import express from"express";import cors from"cors";import{v4 as uuid}from"uuid";import{generateBoard,hasBingo,STAKES,GameState}from"@vamios/shared";
const app=express();app.use(cors());app.use(express.json());const games=new Map<string,GameState>();
app.get("/health",(_,res)=>res.json({ok:true,service:"vamios-api"}));
app.post("/api/games",(req,res)=>{const stake=Number(req.body.stake),boardId=Number(req.body.boardId);if(!STAKES.includes(stake as any)||boardId<1||boardId>100)return res.status(400).send("Invalid stake or board");let g=[...games.values()].find(x=>x.stake===stake&&x.status==="WAITING");if(!g){const now=Date.now();g={id:uuid(),stake,status:"WAITING",createdAt:new Date(now).toISOString(),startsAt:new Date(now+60000).toISOString(),calledNumbers:[],players:[],pot:0};games.set(g.id,g)}if(g.players.some(p=>p.id===req.body.userId))return res.json(g);if(g.players.length>=100)return res.status(409).send("Game full");g.players.push({id:String(req.body.userId||uuid()),displayName:String(req.body.displayName||"Player"),boardId,marked:[]});g.pot+=stake;return res.json(g)});
app.get("/api/games/:id",(req,res)=>{const g=games.get(String(req.params.id));if(!g)return res.sendStatus(404);tick(g);res.json(g)});
app.post("/api/games/:id/mark",(req,res)=>{const g=games.get(String(req.params.id));if(!g)return res.sendStatus(404);const p=g.players.find(x=>x.id===String(req.body.userId));const i=Number(req.body.index);if(!p||i<0||i>24)return res.status(400).send("Invalid player or cell");if(i===12){if(!p.marked.includes(i))p.marked.push(i)}else{p.marked=p.marked.includes(i)?p.marked.filter(x=>x!==i):[...p.marked,i]}res.json(g)});
app.post("/api/games/:id/bingo",(req,res)=>{const g=games.get(String(req.params.id));if(!g)return res.sendStatus(404);const p=g.players.find(x=>x.id===String(req.body.userId));if(!p)return res.status(400).send("Player not found");const board=generateBoard(p.boardId),valid=hasBingo(board,new Set(g.calledNumbers),new Set(p.marked));if(!valid)return res.status(400).send("Not a valid Bingo");g.status="FINISHED";g.winnerId=p.id;g.prize=Math.floor(g.pot*.8*100)/100;g.commission=g.pot-g.prize;g.endsAt=new Date().toISOString();res.json({game:g,valid:true})});
function tick(g:GameState){const now=Date.now();if(g.status==="WAITING"&&g.startsAt&&now>=Date.parse(g.startsAt)){g.status="RUNNING";g.nextCallAt=new Date(now+5000).toISOString()}if(g.status!=="RUNNING")return;if(g.calledNumbers.length>=75){g.status="FINISHED";g.endsAt=new Date().toISOString();return}if(!g.nextCallAt||now>=Date.parse(g.nextCallAt)){const used=new Set(g.calledNumbers);const pool=Array.from({length:75},(_,i)=>i+1).filter(n=>!used.has(n));const n=pool[Math.floor(Math.random()*pool.length)];g.calledNumbers.push(n);g.nextCallAt=new Date(now+5000).toISOString()}}
const port=Number(process.env.PORT||3001);app.listen(port,()=>console.log(`VAMIOS API listening on ${port}`));
